// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"mongmeo.dev/todo/internal/adapter/database/ent/schema"
	"mongmeo.dev/todo/internal/adapter/database/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescIsDone is the schema descriptor for is_done field.
	todoDescIsDone := todoFields[2].Descriptor()
	// todo.DefaultIsDone holds the default value on creation for the is_done field.
	todo.DefaultIsDone = todoDescIsDone.Default.(bool)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[3].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
	// todoDescUpdatedAt is the schema descriptor for updated_at field.
	todoDescUpdatedAt := todoFields[4].Descriptor()
	// todo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todo.DefaultUpdatedAt = todoDescUpdatedAt.Default.(func() time.Time)
}
